dist: xenial
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"   
install:
    - pip install -r requirements.txt
    - pip install . 
script:
    coverage run -m unittest discover -v
after_success:
    coveralls

